<?php

namespace app\api\controller;
/**
 * ============================================================================
 * DSMall多用户商城
 * ============================================================================
 * 版权所有 2014-2028 长沙德尚网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.csdeshang.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * 卖家商品控制器
 */
class Sellergoodsonline extends MobileSeller {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->obj=new Sellergoods($this->app);
    }

    public function goods_list() {
        $this->obj->goods_list();
    }

    public function goods_show() {
        $this->obj->goods_show();
    }

    public function goods_unshow() {
        $this->obj->goods_unshow();
    }

    public function drop_goods() {
        $this->obj->drop_goods();
    }

    public function edit_goods() {
        $this->obj->edit_goods();
    }

    public function goods_class() {
        $this->obj->goods_class();
    }

    public function get_common_data() {
        $this->obj->get_common_data();
    }

    public function save_goods() {
        $this->obj->save_goods();
    }

    public function image_upload() {
        $this->obj->image_upload();
    }
    
    public function video_upload() {
        $this->obj->video_upload();
    }
    
    public function add_spec() {
        $this->obj->add_spec();
    }

    public function edit_image() {
        $this->obj->edit_image();
    }

    public function save_image() {
        $this->obj->save_image();
    }
}
?>
